@startuml
Title Activiteitsdiagram voorbeeld
start
:actie 1;
:actie 2;
if (voorwaarde A?) then (ja)
    :actie 3;
else (nee)
    :actie 4;
    stop
endif
while (voorwaarde B?) is (ja)
    :actie 5;
endwhile (nee)
fork
    :actie 6;
fork again
    :actie 7;
end fork
stop
@enduml
