@startuml
left to right direction

Title Usecasediagram restaurant

:kok: as o
:klant: as k
:ober: as b
:eigenaar: as e
:personeel: as p

b <|-right- e
p <|-right- e
p <|-right- o
p <|-right- b

b -down-> (bedienen)
o -down-> (koken)
k -down-> (eten)
p -down-> (sluiten)
p -down-> (openen)
e -down-> (administatie doen)

@enduml
